{% set name = "JAGS" %}
{% set version = "4.3.1" %}
{% set sha256 = "f9258355b5e9eb13bd33c5fa720f0cbebacea7d0a4a42b71b0fb14501ee14229" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://sourceforge.net/projects/mcmc-jags/files/JAGS/{{ version[0] }}.x/Source/{{ name }}-{{ version }}.tar.gz/
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - liblapack

test:
  commands:
    - jags <<< 'exit'

about:
  home: http://mcmc-jags.sourceforge.net
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  description: |
    JAGS is Just Another Gibbs Sampler. It is a program for analysis of Bayesian
    hierarchical models using Markov Chain Monte Carlo (MCMC) simulation
    not wholly unlike BUGS.
  summary: JAGS is Just Another Gibbs Sampler

extra:
  recipe-maintainers:
    - micknudsen
