travis:
  secure:
    BINSTAR_TOKEN: MteiFtRvIDBYhIX1XN9NVVCt8RscEFiuUXXcm098ClYxYs8vBRlWxeYcYbdVbY7Y2iX3H5V0cahzGfGKAQavp5RUGWj6/vIjsiAbct7FjjEgRiCweoA5woIXJ9Q4X3kC5xVHCrWyFjHzgGrsO+DXBnil7irALbvUuNFNfvSN7GMSoop/WCa0guZDSb4Z16ubmWMhvrLfdP1mxUOtvFfOMoUmBCzMRWIn/kJZxPZo/PvooxJ2wExX+Y1mSSWVDp8iQ4gXuK+hIpzPZEqnvdOH2yAWGvhpPfcymgGixdCaFpFN2miRjQvTiYRXn7AL/fxQAzxf2J8jF/ExVVzYDimOWO3i7Ei2DsvUJGz6MbYJs8k92K36PTk32CEagBln/7QCkoPMeHUomQ213XNGG60ae21CNGTXbUsYCBt5cn3jK6KJUfrxUm4XvvYCVyTCbeYkm8X3ag3SHpJJbfnLGfiGQ0B7FRgGCpxajhMEUvfUiPY/YO5+3c4XKDoOe0T3+wZki9synhKFuIn8oEJTmekEfcUgBuyMCoDi6plgVyf9/7GDjrkOb+ez4XCl3RONDMTIFBFLTo1tGxjcNuGXMzZdRRw5lrpaUQKS8RD5Eq9VZfLs2p6k+B8wXI9PE4e6joI9YK+fpwMk5zxPvqIbs5iuN8n8GcqOtVaq8D6i0NrgS7U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
